# Site settings
author: upbeat-torrent-2014
title: 
header-img: img/home-bg.png
email: ramaabrahams@yahoo.com
copyright_name: upbeat-torrent-2014
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Rama0210

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
